Traceback (most recent call last):
  File "C:\Users\Janareis\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Janareis\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Janareis\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Janareis\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Janareis\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Janareis\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Janareis\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
centered_image_html = """
<div style="display: flex; justify-content: center;">
    <img src='C:\Users\Janareis\cnn-conv_2d\_build\html\_images\inputmatrix.png'  width = 300, height = 300>
</div>
"""


display(HTML(centered_image_html))

------------------


[1;36m  Cell [1;32mIn[4], line 5[1;36m[0m
[1;33m    """[0m
[1;37m       ^[0m
[1;31mSyntaxError[0m[1;31m:[0m (unicode error) 'unicodeescape' codec can't decode bytes in position 71-72: truncated \UXXXXXXXX escape


